import { Download, FileJson, FileText } from "lucide-react";
import { toast } from "sonner";
import { useExportAnalysis } from "@/api/threats";
import { Button } from "@/components/ui/button";

interface ExportPanelProps {
  orgId: string;
  jobId: string;
  analysisData: unknown;
}

export function ExportPanel({ orgId, jobId, analysisData }: ExportPanelProps) {
  const exportAnalysis = useExportAnalysis(orgId, jobId);

  async function handleJsonExport() {
    try {
      await exportAnalysis.mutateAsync();
      toast.success("Download started");
    } catch {
      toast.error("Export failed");
    }
  }

  function handleMarkdownExport() {
    try {
      const md = renderAnalysisAsMarkdown(analysisData);
      const blob = new Blob([md], { type: "text/markdown" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `threat-model-${jobId}.md`;
      a.click();
      URL.revokeObjectURL(url);
      toast.success("Markdown downloaded");
    } catch {
      toast.error("Failed to generate Markdown");
    }
  }

  return (
    <div className="space-y-6 p-4">
      <div>
        <h3 className="text-sm font-semibold">Export threat model</h3>
        <p className="mt-1 text-sm text-muted-foreground">
          Download the full analysis for offline review or integration with other tools.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        <div className="rounded-lg border p-4 space-y-3">
          <div className="flex items-center gap-2">
            <FileJson className="h-5 w-5 text-primary" />
            <span className="font-medium">JSON export</span>
          </div>
          <p className="text-sm text-muted-foreground">
            Full structured analysis blob including all threats, mitigations, mappings, and metadata.
          </p>
          <Button
            onClick={handleJsonExport}
            disabled={exportAnalysis.isPending}
            className="w-full gap-2"
            variant="outline"
          >
            <Download className="h-4 w-4" />
            {exportAnalysis.isPending ? "Downloading…" : "Download JSON"}
          </Button>
        </div>

        <div className="rounded-lg border p-4 space-y-3">
          <div className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />
            <span className="font-medium">Markdown report</span>
          </div>
          <p className="text-sm text-muted-foreground">
            Human-readable threat model report rendered from analysis data.
          </p>
          <Button
            onClick={handleMarkdownExport}
            className="w-full gap-2"
            variant="outline"
          >
            <Download className="h-4 w-4" />
            Download Markdown
          </Button>
        </div>
      </div>
    </div>
  );
}

function renderAnalysisAsMarkdown(data: unknown): string {
  if (!data || typeof data !== "object") return "# Threat Model\n\nNo analysis data available.";
  const d = data as Record<string, unknown>;
  const lines: string[] = [];
  lines.push("# Threat Model Analysis");
  lines.push("");
  if (typeof d["systemSummary"] === "string") {
    lines.push("## System Summary");
    lines.push(d["systemSummary"]);
    lines.push("");
  }
  lines.push("*Generated by Threat Modeling Agent*");
  return lines.join("\n");
}
