// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThreatModelingAgent.Infrastructure.Persistence;

#nullable disable

namespace ThreatModelingAgent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507000000_IncreaseArchitectureDescriptionLength")]
    partial class IncreaseArchitectureDescriptionLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.Architecture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssumptionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("assumptions");

                    b.Property<string>("ClarificationQuestionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("clarification_questions");

                    b.PrimitiveCollection<string[]>("Classification")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeploymentContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("deployment_context");

                    b.Property<string>("GapsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("gaps");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("SystemPurpose")
                        .HasColumnType("text")
                        .HasColumnName("system_purpose");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("OrgId");

                    b.ToTable("architectures", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.ArchitectureCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArchitectureId")
                        .HasColumnType("uuid")
                        .HasColumnName("architecture_id");

                    b.Property<Guid>("CorrectedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("corrected_by");

                    b.Property<string>("CorrectedValue")
                        .HasColumnType("text")
                        .HasColumnName("corrected_value");

                    b.Property<string>("CorrectionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correction_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("element_id");

                    b.Property<string>("FieldName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("OriginalValue")
                        .HasColumnType("text")
                        .HasColumnName("original_value");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureId");

                    b.HasIndex("ElementId");

                    b.ToTable("architecture_corrections", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.ArchitectureElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArchitectureId")
                        .HasColumnType("uuid")
                        .HasColumnName("architecture_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("element_type");

                    b.Property<string>("ExtractionConfidence")
                        .HasColumnType("text")
                        .HasColumnName("extraction_confidence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ArchitectureId");

                    b.HasIndex("ArchitectureId", "ElementType");

                    b.ToTable("architecture_elements", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "CreatedAt");

                    b.HasIndex("OrgId", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.FrameworkMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Framework")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("framework");

                    b.Property<string>("MappingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mapping_type");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<Guid>("ThreatId")
                        .HasColumnType("uuid")
                        .HasColumnName("threat_id");

                    b.HasKey("Id");

                    b.HasIndex("ThreatId");

                    b.ToTable("framework_mappings", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("application_description");

                    b.Property<string>("ArchitectureDescription")
                        .HasColumnType("text")
                        .HasColumnName("architecture_description");

                    b.Property<string>("ArtifactBlobPath")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("artifact_blob_path");

                    b.Property<string>("ArtifactType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("artifact_type");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("LlmTokenUsageJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("llm_token_usage");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("OrgId", "CreatedAt");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.Mitigation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<Guid>("ThreatId")
                        .HasColumnType("uuid")
                        .HasColumnName("threat_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ThreatId");

                    b.ToTable("mitigations", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.OrgIdpConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string[]>("DomainHints")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("domain_hints");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkOsConnectionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("workos_connection_id");

                    b.HasKey("Id");

                    b.HasIndex("OrgId")
                        .IsUnique();

                    b.ToTable("org_idp_configs", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.OrgMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.HasIndex("UserId");

                    b.HasIndex("OrgId", "UserId")
                        .IsUnique();

                    b.ToTable("org_memberships", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_suspended");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkOsOrgId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("workos_org_id");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("WorkOsOrgId")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.RejectedCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("MethodCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("method_category");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("RejectionNote")
                        .HasColumnType("text")
                        .HasColumnName("rejection_note");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("rejected_candidates", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.Threat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<Guid[]>("AffectedElementIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("affected_element_ids");

                    b.Property<string>("Assumptions")
                        .HasColumnType("text")
                        .HasColumnName("assumptions");

                    b.Property<string>("AttackScenario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attack_scenario");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("confidence");

                    b.Property<string>("ControlGaps")
                        .HasColumnType("text")
                        .HasColumnName("control_gaps");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string[]>("EvidenceBasis")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("evidence_basis");

                    b.Property<string>("EvidenceStrength")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evidence_strength");

                    b.Property<string>("ExistingControls")
                        .HasColumnType("text")
                        .HasColumnName("existing_controls");

                    b.Property<string>("FindingType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("finding_type");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("identifier");

                    b.PrimitiveCollection<string[]>("ImpactedAssets")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("impacted_assets");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("MethodCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("method_category");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Preconditions")
                        .HasColumnType("text")
                        .HasColumnName("preconditions");

                    b.Property<string>("PrivacyImpact")
                        .HasColumnType("text")
                        .HasColumnName("privacy_impact");

                    b.Property<string>("RiskRatingJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_rating");

                    b.Property<string>("SecurityImpact")
                        .HasColumnType("text")
                        .HasColumnName("security_impact");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobId", "FindingType");

                    b.HasIndex("JobId", "Identifier")
                        .IsUnique();

                    b.ToTable("threats", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.ThreatNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<Guid>("ThreatId")
                        .HasColumnType("uuid")
                        .HasColumnName("threat_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ThreatId");

                    b.ToTable("threat_notes", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkOsUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("workos_user_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkOsUserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.ArchitectureCorrection", b =>
                {
                    b.HasOne("ThreatModelingAgent.Domain.Entities.Architecture", null)
                        .WithMany("Corrections")
                        .HasForeignKey("ArchitectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThreatModelingAgent.Domain.Entities.ArchitectureElement", null)
                        .WithMany("Corrections")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.ArchitectureElement", b =>
                {
                    b.HasOne("ThreatModelingAgent.Domain.Entities.Architecture", null)
                        .WithMany("Elements")
                        .HasForeignKey("ArchitectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.FrameworkMapping", b =>
                {
                    b.HasOne("ThreatModelingAgent.Domain.Entities.Threat", null)
                        .WithMany("FrameworkMappings")
                        .HasForeignKey("ThreatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.Mitigation", b =>
                {
                    b.HasOne("ThreatModelingAgent.Domain.Entities.Threat", null)
                        .WithMany("Mitigations")
                        .HasForeignKey("ThreatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.ThreatNote", b =>
                {
                    b.HasOne("ThreatModelingAgent.Domain.Entities.Threat", null)
                        .WithMany("Notes")
                        .HasForeignKey("ThreatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.Architecture", b =>
                {
                    b.Navigation("Corrections");

                    b.Navigation("Elements");
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.ArchitectureElement", b =>
                {
                    b.Navigation("Corrections");
                });

            modelBuilder.Entity("ThreatModelingAgent.Domain.Entities.Threat", b =>
                {
                    b.Navigation("FrameworkMappings");

                    b.Navigation("Mitigations");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
