using ThreatModelingAgent.Domain.Enums;
using ThreatModelingAgent.Domain.ValueObjects;

namespace ThreatModelingAgent.Domain.Entities;

/// <summary>
/// A threat generated by the analysis pipeline or added by a user.
/// Spec: data-model §4.9, product spec §11.
///
/// Invariants (spec data-model §9):
/// - Confidence = High MUST NOT be set unless FindingType = Confirmed
/// - Identifier MUST be unique within a job and follow the format T-NNN
/// - User-added threats MUST reference at least one architecture element
/// </summary>
public class Threat
{
    public Guid Id { get; private set; }
    public JobId JobId { get; private set; }
    public OrgId OrgId { get; private set; }
    public string Identifier { get; private set; } = string.Empty;  // T-001, T-002, ...
    public string Title { get; private set; } = string.Empty;
    public string MethodCategory { get; private set; } = string.Empty;
    public Guid[] AffectedElementIds { get; private set; } = [];
    public string Description { get; private set; } = string.Empty;
    public string AttackScenario { get; private set; } = string.Empty;
    public string? Preconditions { get; private set; }
    public string[] ImpactedAssets { get; private set; } = [];
    public string? SecurityImpact { get; private set; }
    public string? PrivacyImpact { get; private set; }
    public string? ExistingControls { get; private set; }
    public string? ControlGaps { get; private set; }
    public ConfidenceLevel Confidence { get; private set; }
    public string[] EvidenceBasis { get; private set; } = [];
    public EvidenceStrength EvidenceStrength { get; private set; }
    public string? Assumptions { get; private set; }
    public FindingType FindingType { get; private set; }
    public ThreatStatus Status { get; private set; }
    public string Source { get; private set; } = string.Empty;     // system | user
    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset UpdatedAt { get; private set; }

    // Navigation
    public ICollection<ThreatNote> Notes { get; private set; } = [];
    public ICollection<Mitigation> Mitigations { get; private set; } = [];
    public ICollection<FrameworkMapping> FrameworkMappings { get; private set; } = [];

    private Threat() { }

    public static Threat CreateFromPipeline(
        JobId jobId,
        OrgId orgId,
        string identifier,
        string title,
        string methodCategory,
        Guid[] affectedElementIds,
        string description,
        string attackScenario,
        string? preconditions,
        string[] impactedAssets,
        string? securityImpact,
        string? privacyImpact,
        string? existingControls,
        string? controlGaps,
        ConfidenceLevel confidence,
        string[] evidenceBasis,
        EvidenceStrength evidenceStrength,
        string? assumptions,
        FindingType findingType)
    {
        // Invariant: High confidence MUST NOT be set on conditional findings (spec §9)
        if (confidence == ConfidenceLevel.High && findingType == FindingType.Conditional)
            throw new ArgumentException(
                "Confidence cannot be High for a Conditional finding (spec data-model §9).");

        ValidateIdentifier(identifier);

        var now = DateTimeOffset.UtcNow;
        return new Threat
        {
            Id = Guid.NewGuid(),
            JobId = jobId,
            OrgId = orgId,
            Identifier = identifier,
            Title = title,
            MethodCategory = methodCategory,
            AffectedElementIds = affectedElementIds,
            Description = description,
            AttackScenario = attackScenario,
            Preconditions = preconditions,
            ImpactedAssets = impactedAssets,
            SecurityImpact = securityImpact,
            PrivacyImpact = privacyImpact,
            ExistingControls = existingControls,
            ControlGaps = controlGaps,
            Confidence = confidence,
            EvidenceBasis = evidenceBasis,
            EvidenceStrength = evidenceStrength,
            Assumptions = assumptions,
            FindingType = findingType,
            Status = ThreatStatus.Open,
            Source = "system",
            CreatedAt = now,
            UpdatedAt = now
        };
    }

    public static Threat CreateUserAdded(
        JobId jobId,
        OrgId orgId,
        string identifier,
        string title,
        string methodCategory,
        Guid[] affectedElementIds,
        string description,
        string attackScenario)
    {
        // Invariant: user-added threats MUST reference at least one architecture element (spec data-model §9)
        if (affectedElementIds.Length == 0)
            throw new ArgumentException(
                "A user-added threat must reference at least one architecture element (spec data-model §9).",
                nameof(affectedElementIds));

        ValidateIdentifier(identifier);

        var now = DateTimeOffset.UtcNow;
        return new Threat
        {
            Id = Guid.NewGuid(),
            JobId = jobId,
            OrgId = orgId,
            Identifier = identifier,
            Title = title,
            MethodCategory = methodCategory,
            AffectedElementIds = affectedElementIds,
            Description = description,
            AttackScenario = attackScenario,
            Confidence = ConfidenceLevel.Medium,
            EvidenceBasis = ["explicit_user_provided_fact"],
            EvidenceStrength = EvidenceStrength.Direct,
            FindingType = FindingType.UserAdded,
            ImpactedAssets = [],
            Status = ThreatStatus.Open,
            Source = "user",
            CreatedAt = now,
            UpdatedAt = now
        };
    }

    public void UpdateStatus(ThreatStatus newStatus)
    {
        Status = newStatus;
        UpdatedAt = DateTimeOffset.UtcNow;
    }

    private static void ValidateIdentifier(string identifier)
    {
        if (!System.Text.RegularExpressions.Regex.IsMatch(identifier, @"^T-\d{3,}$"))
            throw new ArgumentException(
                $"Threat identifier must match T-NNN format. Got: {identifier}", nameof(identifier));
    }
}
